### ISSUE TITLE
Error building conduit in cray environment - without MPI

### ISSUE THREAD

**Issue by dyokelson** [LLNL/conduit#1106]
Hello, I'm trying to install conduit (within another cmake project) on LUMI, which is a cray cluster kind of similar to Frontier (https://docs.lumi-supercomputer.eu/hardware/). Since I am using cray-mpich I try to install conduit without mpi support, otherwise the conduit install fails during the cmake step. However, now I am getting the error I pasted below during the 'build' setp. Any ideas for what might work on this machine? Thanks!

The modules I have loaded are: 
```
Currently Loaded Modules:
  1) perftools-base/22.12.0                     10) craype/2.7.19
  2) cce/15.0.0                                 11) cray-dsmml/0.2.2
  3) ModuleLabel/label                     (S)  12) cray-mpich/8.1.23
  4) lumi-tools/23.03                      (S)  13) cray-libsci/22.12.1.1
  5) init-lumi/0.2                         (S)  14) PrgEnv-cray/8.3.3
  6) craype-x86-rome                            15) craype-accel-amd-gfx90a
  7) libfabric/1.15.2.0                         16) rocm/5.2.3
  8) craype-network-ofi                         17) cray-python/3.9.13.1
  9) xpmem/2.5.2-2.4_3.20__gd0f7936.shasta      18) spack/22.08-2
```

And the part of spack.yaml that I think are most related looks like this: 
```
spack:
  specs:
  - uuid %cce@15.0.0
  - cppunit %cce@15.0.0
  - mochi-bedrock %cce@15.0.0 ^mercury@master
  - conduit@develop %cce@15.0.0 ~mpi~silo
  concretizer:
    unify: true
    reuse: true
  modules:
    prefix_inspections:
      lib: [LD_LIBRARY_PATH]
      lib64: [LD_LIBRARY_PATH]
  repos:
  - /pfs/lustrep1/users/dewiy/soma-collector/mochi-spack-packages
  packages:
    mpi:
      buildable: false
    mpich:
      externals:
      - spec: mpich@8.1.23
        modules: [cray-mpich]
      buildable: false
    libfabric:
      externals:
      - spec: libfabric@1.15.2.0
        modules: [libfabric]
      buildable: false
    hdf5:
      externals:
      - spec: hdf5@1.12.2.1
        modules: [cray-hdf5]
      buildable: false
    libdrm:
      externals:
      - spec: libdrm@2.4.110
        modules: [libdrm]
      buildable: false
    all:
      require: '%cce@15.0.0'
      providers:
        mpi: [mpich, cray-mpich]
```

```
[+] /appl/lumi/SW/CrayEnv/EB/buildtools/22.08 (external cmake-3.24.0-gdqd4yjymaafus53hxgqb7poq4vgn6cg)
==> hdf5@1.12.2.1 : has external module in ['cray-hdf5']
[+] /opt/cray/pe/hdf5/1.12.2.1 (external hdf5-1.12.2.1-5f3fk6hkvc7vjc3ur3iizt7fujkgwmqb)
==> cray-mpich@8.1.18 : has external module in ['cray-mpich/8.1.18']
[+] /opt/cray/pe/mpich/8.1.18/ofi/crayclang/10.0 (external cray-mpich-8.1.18-svq6xvw2qqald54ljz5knyzadiyblxur)
[+] /project/project_462000129/spack/22.08/0.19.0/metis-5.1.0-a2a2753
[+] /project/project_462000129/spack/22.08/0.19.0/parmetis-4.0.3-t2kx7fi
==> Installing conduit-develop-m5quym3mfeanphprw3h6ssf3ctsxsge2
==> conduit exists in binary cache but with different hash
==> No binary for conduit-develop-m5quym3mfeanphprw3h6ssf3ctsxsge2 found: installing from source
==> No patches needed for conduit
==> conduit: Executing phase: 'cmake'
==> conduit: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j32'

139 errors found in build log:
     1236    [ 43%] Linking CXX executable t_conduit_node_static_init
     1237    cd /tmp/dewiy/spack-stage/spack-stage-conduit-develop-m5quym3mfeanphprw3h6ssf3ctsxsge2/
             spack-build-m5quym3/tests/conduit && /pfs/lustrep1/appl/lumi/SW/CrayEnv/EB/buildtools/2
             2.08/bin/cmake -E cmake_link_script CMakeFiles/t_conduit_node_static_init.dir/link.txt 
             --verbose=1
     1238    /opt/cray/pe/craype/2.7.19/bin/CC -O2 -g -DNDEBUG -dynamic CMakeFiles/t_conduit_node_st
             atic_init.dir/t_conduit_node_static_init.cpp.o -o t_conduit_node_static_init  -Wl,-rpat
             h,/tmp/dewiy/spack-stage/spack-stage-conduit-develop-m5quym3mfeanphprw3h6ssf3ctsxsge2/s
             pack-build-m5quym3/lib ../../lib/libconduit.so ../../lib/libgtest_main.so ../../lib/lib
             gtest.so
     1239    [ 43%] Linking CXX executable t_conduit_node_parent
     1240    cd /tmp/dewiy/spack-stage/spack-stage-conduit-develop-m5quym3mfeanphprw3h6ssf3ctsxsge2/
             spack-build-m5quym3/tests/conduit && /pfs/lustrep1/appl/lumi/SW/CrayEnv/EB/buildtools/2
             2.08/bin/cmake -E cmake_link_script CMakeFiles/t_conduit_node_parent.dir/link.txt --ver
             bose=1
     1241    /opt/cray/pe/craype/2.7.19/bin/CC -O2 -g -DNDEBUG -dynamic CMakeFiles/t_conduit_node_pa
             rent.dir/t_conduit_node_parent.cpp.o -o t_conduit_node_parent  -Wl,-rpath,/tmp/dewiy/sp
             ack-stage/spack-stage-conduit-develop-m5quym3mfeanphprw3h6ssf3ctsxsge2/spack-build-m5qu
             ym3/lib ../../lib/libconduit.so ../../lib/libgtest_main.so ../../lib/libgtest.so
  >> 1242    ld.lld: error: undefined reference due to --no-allow-shlib-undefined: .omp_offloading.i
             mg_start.cray_amdgcn-amd-amdhsa
     1243    >>> referenced by ../../lib/libconduit.so
     1244    
  >> 1245    ld.lld: error: undefined reference due to --no-allow-shlib-undefined: .omp_offloading.i
             mg_size.cray_amdgcn-amd-amdhsa
     1246    >>> referenced by ../../lib/libconduit.so
     1247    
  >> 1248    ld.lld: error: undefined reference due to --no-allow-shlib-undefined: .omp_offloading.i
             mg_cache.cray_amdgcn-amd-amdhsa
     1249    >>> referenced by ../../lib/libconduit.so
  >> 1250    clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
  >> 1251    make[2]: *** [tests/conduit/CMakeFiles/t_conduit_smoke.dir/build.make:103: tests/condui
             t/t_conduit_smoke] Error 1
```

**Comment by cyrush** [comment]
@dyokelson This looks related to OpenMP, we had a recent addition to conduit that is using OpenMP, but it seems the build system logic isn't fully ready. 

Would you be willing to try applying this patch via spack to see if it resolves the issue:

```
diff --git a/src/libs/conduit/conduit_execution.hpp b/src/libs/conduit/conduit_execution.hpp
index 0c61d837..17819452 100644
--- a/src/libs/conduit/conduit_execution.hpp
+++ b/src/libs/conduit/conduit_execution.hpp
@@ -15,7 +15,7 @@
 // conduit lib includes
 //-----------------------------------------------------------------------------
 #include "conduit_execution_serial.hpp"
-#include "conduit_execution_omp.hpp"
+//#include "conduit_execution_omp.hpp"
 
 //-----------------------------------------------------------------------------
 // -- begin conduit --
```

**Comment by dyokelson** [comment]
Sure! But I have never applied a patch with spack before so I'm not familiar and just looked at the documentation. I just copy that and save it as a .patch file and then put it here? "/pfs/lustrep1/appl/lumi/spack/22.08/0.19.0-user/var/spack/repos/builtin/packages/conduit"
And it should apply after the download?

**Comment by dyokelson** [comment]
It seems I cannot write to that directory, I probably will need to use my own spack installation instead of the module on the cluster - doing this now

**Comment by cyrush** [comment]
You would add that as a patch file, and also a statement in the Conduit python package that looks like:

```
patch("mypatch.patch")
```

**Comment by dyokelson** [comment]
Ok, got it to apply the patch, new error now, haha. Maybe still has some openmp references somewhere? It looks like it didn't get as far this time.

```
==> Installing conduit-develop-guzu3vmeje4p3gcgxrbgrqw2mkcmmjhg
==> No binary for conduit-develop-guzu3vmeje4p3gcgxrbgrqw2mkcmmjhg found: installing from source
==> Applied patch /pfs/lustrep2/projappl/project_462000129/spack2/var/spack/repos/builtin/packages/conduit/openmp.patch
==> conduit: Executing phase: 'cmake'
==> conduit: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16'

76 errors found in build log:
     871     cd /tmp/dewiy/spack-stage/spack-stage-conduit-develop-guzu3vmeje4p3gcgxrbgrqw2mkcmmjhg/spack-bui
             ld-guzu3vm/libs/blueprint && /opt/cray/pe/craype/2.7.19/bin/CC -Dconduit_blueprint_EXPORTS -I/tm
             p/dewiy/spack-stage/spack-stage-conduit-develop-guzu3vmeje4p3gcgxrbgrqw2mkcmmjhg/spack-build-guz
             u3vm/fortran -I/tmp/dewiy/spack-stage/spack-stage-conduit-develop-guzu3vmeje4p3gcgxrbgrqw2mkcmmj
             hg/spack-src/src/libs/conduit -I/tmp/dewiy/spack-stage/spack-stage-conduit-develop-guzu3vmeje4p3
             gcgxrbgrqw2mkcmmjhg/spack-src/src/libs/conduit/c -I/tmp/dewiy/spack-stage/spack-stage-conduit-de
             velop-guzu3vmeje4p3gcgxrbgrqw2mkcmmjhg/spack-build-guzu3vm/libs/conduit -I/tmp/dewiy/spack-stage
             /spack-stage-conduit-develop-guzu3vmeje4p3gcgxrbgrqw2mkcmmjhg/spack-src/src/libs/relay -I/tmp/de
             wiy/spack-stage/spack-stage-conduit-develop-guzu3vmeje4p3gcgxrbgrqw2mkcmmjhg/spack-src/src/libs/
             relay/c -I/tmp/dewiy/spack-stage/spack-stage-conduit-develop-guzu3vmeje4p3gcgxrbgrqw2mkcmmjhg/sp
             ack-build-guzu3vm/libs/relay -I/tmp/dewiy/spack-stage/spack-stage-conduit-develop-guzu3vmeje4p3g
             cgxrbgrqw2mkcmmjhg/spack-src/src/libs/blueprint -I/tmp/dewiy/spack-stage/spack-stage-conduit-dev
             elop-guzu3vmeje4p3gcgxrbgrqw2mkcmmjhg/spack-src/src/libs/blueprint/c -I/tmp/dewiy/spack-stage/sp
             ack-stage-conduit-develop-guzu3vmeje4p3gcgxrbgrqw2mkcmmjhg/spack-build-guzu3vm/libs/blueprint -I
             /tmp/dewiy/spack-stage/spack-stage-conduit-develop-guzu3vmeje4p3gcgxrbgrqw2mkcmmjhg/spack-src/sr
             c/thirdparty_builtin/rapidjson/include -I/tmp/dewiy/spack-stage/spack-stage-conduit-develop-guzu
             3vmeje4p3gcgxrbgrqw2mkcmmjhg/spack-src/src/thirdparty_builtin/libb64-1.2.1/include -I/tmp/dewiy/
             spack-stage/spack-stage-conduit-develop-guzu3vmeje4p3gcgxrbgrqw2mkcmmjhg/spack-src/src/thirdpart
             y_builtin/libyaml-690a781/include -I/tmp/dewiy/spack-stage/spack-stage-conduit-develop-guzu3vmej
             e4p3gcgxrbgrqw2mkcmmjhg/spack-src/src/thirdparty_builtin/fmt-7.1.0 -I/tmp/dewiy/spack-stage/spac
             k-stage-conduit-develop-guzu3vmeje4p3gcgxrbgrqw2mkcmmjhg/spack-src/src/thirdparty_builtin/civetw
             eb-0a95342/include -I/pfs/lustrep2/projappl/project_462000129/spack2/opt/spack/linux-sles15-zen2
             /cce-15.0.0/parmetis-4.0.3-kp42fdwdcoelobfo4phrmpujn7hs33sd/include -O2 -g -DNDEBUG -fPIC   -Wal
             l -Wextra -std=c++11 -MD -MT libs/blueprint/CMakeFiles/conduit_blueprint.dir/conduit_blueprint_m
             esh_flatten.cpp.o -MF CMakeFiles/conduit_blueprint.dir/conduit_blueprint_mesh_flatten.cpp.o.d -o
              CMakeFiles/conduit_blueprint.dir/conduit_blueprint_mesh_flatten.cpp.o -c /tmp/dewiy/spack-stage
             /spack-stage-conduit-develop-guzu3vmeje4p3gcgxrbgrqw2mkcmmjhg/spack-src/src/libs/blueprint/condu
             it_blueprint_mesh_flatten.cpp
     872     make[2]: Leaving directory '/tmp/dewiy/spack-stage/spack-stage-conduit-develop-guzu3vmeje4p3gcgx
             rbgrqw2mkcmmjhg/spack-build-guzu3vm'
     873     [ 22%] Built target t_f_conduit_node_int
     874     [ 22%] Building CXX object libs/blueprint/CMakeFiles/conduit_blueprint.dir/conduit_blueprint_mca
             rray.cpp.o
     875     cd /tmp/dewiy/spack-stage/spack-stage-conduit-develop-guzu3vmeje4p3gcgxrbgrqw2mkcmmjhg/spack-bui
             ld-guzu3vm/libs/blueprint && /opt/cray/pe/craype/2.7.19/bin/CC -Dconduit_blueprint_EXPORTS -I/tm
             p/dewiy/spack-stage/spack-stage-conduit-develop-guzu3vmeje4p3gcgxrbgrqw2mkcmmjhg/spack-build-guz
             u3vm/fortran -I/tmp/dewiy/spack-stage/spack-stage-conduit-develop-guzu3vmeje4p3gcgxrbgrqw2mkcmmj
             hg/spack-src/src/libs/conduit -I/tmp/dewiy/spack-stage/spack-stage-conduit-develop-guzu3vmeje4p3
             gcgxrbgrqw2mkcmmjhg/spack-src/src/libs/conduit/c -I/tmp/dewiy/spack-stage/spack-stage-conduit-de
             velop-guzu3vmeje4p3gcgxrbgrqw2mkcmmjhg/spack-build-guzu3vm/libs/conduit -I/tmp/dewiy/spack-stage
             /spack-stage-conduit-develop-guzu3vmeje4p3gcgxrbgrqw2mkcmmjhg/spack-src/src/libs/relay -I/tmp/de
             wiy/spack-stage/spack-stage-conduit-develop-guzu3vmeje4p3gcgxrbgrqw2mkcmmjhg/spack-src/src/libs/
             relay/c -I/tmp/dewiy/spack-stage/spack-stage-conduit-develop-guzu3vmeje4p3gcgxrbgrqw2mkcmmjhg/sp
             ack-build-guzu3vm/libs/relay -I/tmp/dewiy/spack-stage/spack-stage-conduit-develop-guzu3vmeje4p3g
             cgxrbgrqw2mkcmmjhg/spack-src/src/libs/blueprint -I/tmp/dewiy/spack-stage/spack-stage-conduit-dev
             elop-guzu3vmeje4p3gcgxrbgrqw2mkcmmjhg/spack-src/src/libs/blueprint/c -I/tmp/dewiy/spack-stage/sp
             ack-stage-conduit-develop-guzu3vmeje4p3gcgxrbgrqw2mkcmmjhg/spack-build-guzu3vm/libs/blueprint -I
             /tmp/dewiy/spack-stage/spack-stage-conduit-develop-guzu3vmeje4p3gcgxrbgrqw2mkcmmjhg/spack-src/sr
             c/thirdparty_builtin/rapidjson/include -I/tmp/dewiy/spack-stage/spack-stage-conduit-develop-guzu
             3vmeje4p3gcgxrbgrqw2mkcmmjhg/spack-src/src/thirdparty_builtin/libb64-1.2.1/include -I/tmp/dewiy/
             spack-stage/spack-stage-conduit-develop-guzu3vmeje4p3gcgxrbgrqw2mkcmmjhg/spack-src/src/thirdpart
             y_builtin/libyaml-690a781/include -I/tmp/dewiy/spack-stage/spack-stage-conduit-develop-guzu3vmej
             e4p3gcgxrbgrqw2mkcmmjhg/spack-src/src/thirdparty_builtin/fmt-7.1.0 -I/tmp/dewiy/spack-stage/spac
             k-stage-conduit-develop-guzu3vmeje4p3gcgxrbgrqw2mkcmmjhg/spack-src/src/thirdparty_builtin/civetw
             eb-0a95342/include -I/pfs/lustrep2/projappl/project_462000129/spack2/opt/spack/linux-sles15-zen2
             /cce-15.0.0/parmetis-4.0.3-kp42fdwdcoelobfo4phrmpujn7hs33sd/include -O2 -g -DNDEBUG -fPIC   -Wal
             l -Wextra -std=c++11 -MD -MT libs/blueprint/CMakeFiles/conduit_blueprint.dir/conduit_blueprint_m
             carray.cpp.o -MF CMakeFiles/conduit_blueprint.dir/conduit_blueprint_mcarray.cpp.o.d -o CMakeFile
             s/conduit_blueprint.dir/conduit_blueprint_mcarray.cpp.o -c /tmp/dewiy/spack-stage/spack-stage-co
             nduit-develop-guzu3vmeje4p3gcgxrbgrqw2mkcmmjhg/spack-src/src/libs/blueprint/conduit_blueprint_mc
             array.cpp
     876     In file included from /tmp/dewiy/spack-stage/spack-stage-conduit-develop-guzu3vmeje4p3gcgxrbgrqw
             2mkcmmjhg/spack-src/src/libs/blueprint/conduit_blueprint_mesh_topology_metadata.cpp:27:
  >> 877     /tmp/dewiy/spack-stage/spack-stage-conduit-develop-guzu3vmeje4p3gcgxrbgrqw2mkcmmjhg/spack-src/sr
             c/libs/conduit/conduit_execution.hpp:44:24: error: use of undeclared identifier 'omp'
     878         using for_policy = omp::for_policy;
     879                            ^
  >> 880     /tmp/dewiy/spack-stage/spack-stage-conduit-develop-guzu3vmeje4p3gcgxrbgrqw2mkcmmjhg/spack-src/sr
             c/libs/conduit/conduit_execution.hpp:45:25: error: use of undeclared identifier 'omp'
     881         using sort_policy = omp::sort_policy;
     882                             ^
     883     [ 22%] Building CXX object libs/blueprint/CMakeFiles/conduit_blueprint.dir/conduit_blueprint_mca
             rray_examples.cpp.o
     884     cd /tmp/dewiy/spack-stage/spack-stage-conduit-develop-guzu3vmeje4p3gcgxrbgrqw2mkcmmjhg/spack-bui
             ld-guzu3vm/libs/blueprint && /opt/cray/pe/craype/2.7.19/bin/CC -Dconduit_blueprint_EXPORTS -I/tm
             p/dewiy/spack-stage/spack-stage-conduit-develop-guzu3vmeje4p3gcgxrbgrqw2mkcmmjhg/spack-build-guz
             u3vm/fortran -I/tmp/dewiy/spack-stage/spack-stage-conduit-develop-guzu3vmeje4p3gcgxrbgrqw2mkcmmj
             hg/spack-src/src/libs/conduit -I/tmp/dewiy/spack-stage/spack-stage-conduit-develop-guzu3vmeje4p3
             gcgxrbgrqw2mkcmmjhg/spack-src/src/libs/conduit/c -I/tmp/dewiy/spack-stage/spack-stage-conduit-de
             velop-guzu3vmeje4p3gcgxrbgrqw2mkcmmjhg/spack-build-guzu3vm/libs/conduit -I/tmp/dewiy/spack-stage
             /spack-stage-conduit-develop-guzu3vmeje4p3gcgxrbgrqw2mkcmmjhg/spack-src/src/libs/relay -I/tmp/de
             wiy/spack-stage/spack-stage-conduit-develop-guzu3vmeje4p3gcgxrbgrqw2mkcmmjhg/spack-src/src/libs/
             relay/c -I/tmp/dewiy/spack-stage/spack-stage-conduit-develop-guzu3vmeje4p3gcgxrbgrqw2mkcmmjhg/sp
             ack-build-guzu3vm/libs/relay -I/tmp/dewiy/spack-stage/spack-stage-conduit-develop-guzu3vmeje4p3g
             cgxrbgrqw2mkcmmjhg/spack-src/src/libs/blueprint -I/tmp/dewiy/spack-stage/spack-stage-conduit-dev
             elop-guzu3vmeje4p3gcgxrbgrqw2mkcmmjhg/spack-src/src/libs/blueprint/c -I/tmp/dewiy/spack-stage/sp
             ack-stage-conduit-develop-guzu3vmeje4p3gcgxrbgrqw2mkcmmjhg/spack-build-guzu3vm/libs/blueprint -I
             /tmp/dewiy/spack-stage/spack-stage-conduit-develop-guzu3vmeje4p3gcgxrbgrqw2mkcmmjhg/spack-src/sr
             c/thirdparty_builtin/rapidjson/include -I/tmp/dewiy/spack-stage/spack-stage-conduit-develop-guzu
             3vmeje4p3gcgxrbgrqw2mkcmmjhg/spack-src/src/thirdparty_builtin/libb64-1.2.1/include -I/tmp/dewiy/
             spack-stage/spack-stage-conduit-develop-guzu3vmeje4p3gcgxrbgrqw2mkcmmjhg/spack-src/src/thirdpart
             y_builtin/libyaml-690a781/include -I/tmp/dewiy/spack-stage/spack-stage-conduit-develop-guzu3vmej
             e4p3gcgxrbgrqw2mkcmmjhg/spack-src/src/thirdparty_builtin/fmt-7.1.0 -I/tmp/dewiy/spack-stage/spac
             k-stage-conduit-develop-guzu3vmeje4p3gcgxrbgrqw2mkcmmjhg/spack-src/src/thirdparty_builtin/civetw
             eb-0a95342/include -I/pfs/lustrep2/projappl/project_462000129/spack2/opt/spack/linux-sles15-zen2
             /cce-15.0.0/parmetis-4.0.3-kp42fdwdcoelobfo4phrmpujn7hs33sd/include -O2 -g -DNDEBUG -fPIC   -Wal
             l -Wextra -std=c++11 -MD -MT libs/blueprint/CMakeFiles/conduit_blueprint.dir/conduit_blueprint_m
             carray_examples.cpp.o -MF CMakeFiles/conduit_blueprint.dir/conduit_blueprint_mcarray_examples.cp
             p.o.d -o CMakeFiles/conduit_blueprint.dir/conduit_blueprint_mcarray_examples.cpp.o -c /tmp/dewiy
             /spack-stage/spack-stage-conduit-develop-guzu3vmeje4p3gcgxrbgrqw2mkcmmjhg/spack-src/src/libs/blu
             eprint/conduit_blueprint_mcarray_examples.cpp
     885     
     886     

     ...

     905     Cray Fortran : 0 errors, 4 warnings, 0 other messages, 0 ansi
     906     Cray Fortran : "explain ftn-message number" gives more information about each message.
     907     /pfs/lustrep3/appl/lumi/SW/CrayEnv/EB/buildtools/22.08/bin/cmake -E cmake_copy_f90_mod fortran/f
             _conduit_node_obj.mod tests/conduit/fortran/CMakeFiles/t_f_conduit_node_obj.dir/f_conduit_node_o
             bj.mod.stamp Cray
     908     [ 23%] Linking Fortran executable t_f_conduit_node_obj
     909     cd /tmp/dewiy/spack-stage/spack-stage-conduit-develop-guzu3vmeje4p3gcgxrbgrqw2mkcmmjhg/spack-bui
             ld-guzu3vm/tests/conduit/fortran && /pfs/lustrep3/appl/lumi/SW/CrayEnv/EB/buildtools/22.08/bin/c
             make -E cmake_link_script CMakeFiles/t_f_conduit_node_obj.dir/link.txt --verbose=1
     910     /opt/cray/pe/craype/2.7.19/bin/ftn -dynamic  -ef CMakeFiles/t_f_conduit_node_obj.dir/t_f_conduit
             _node_obj.f90.o -o t_f_conduit_node_obj  -Wl,-rpath,/tmp/dewiy/spack-stage/spack-stage-conduit-d
             evelop-guzu3vmeje4p3gcgxrbgrqw2mkcmmjhg/spack-build-guzu3vm/lib ../../../lib/libfruit.so ../../.
             ./lib/libconduit.so
  >> 911     /tmp/dewiy/spack-stage/spack-stage-conduit-develop-guzu3vmeje4p3gcgxrbgrqw2mkcmmjhg/spack-src/sr
             c/libs/conduit/conduit_execution.hpp:53:46: error: no type named 'for_policy' in 'conduit::execu
             tion::OpenMPExec'
     912         using policy = typename ExecutionPolicy::for_policy;
```

**Comment by cyrush** [comment]
I see -- there was more to contain.

I'll work on a fix for this.

**Comment by dyokelson** [comment]
Awesome, thank you.

**Comment by cyrush** [comment]
@dyokelson I just merged https://github.com/LLNL/conduit/pull/1107, which I think will resolve the issue.

You should be able to test this by building `conduit@develop` (as you were before with spack) without any patches. 

Let me know how it goes and if there are further issue we will work though them.

**Comment by dyokelson** [comment]
Thank you, I just tried it after running 'rm -rf spack.lock .spack*' in my environment as well as deleting and recloning the whole spack directory (to make sure it downloads the new version of conduit and not something cached). But it seems to get the same omp error. Do you know if there is a way to check if it is for sure downloading the newest version? It doesn't seem like it's "fetching" any new source code. I'm going to reinstall my whole app too.

My spack.yaml says -conduit@develop \~mpi\~silo and reuse: false

```
==> Installing conduit-develop-cmdq4kg4jmo6gmayedefbvbqd3oevnkb
==> No binary for conduit-develop-cmdq4kg4jmo6gmayedefbvbqd3oevnkb found: installing from source
==> No patches needed for conduit
==> conduit: Executing phase: 'cmake'
==> conduit: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16'

43 errors found in build log:
     1102    [ 36%] Linking CXX executable t_conduit_version
     1103    cd /tmp/dewiy/spack-stage/spack-stage-conduit-develop-cmdq4kg4jmo6gmayedefbvbqd3oevnkb/spack-bui
             ld-cmdq4kg/tests/conduit && /pfs/lustrep1/appl/lumi/SW/CrayEnv/EB/buildtools/22.08/bin/cmake -E 
             cmake_link_script CMakeFiles/t_conduit_version.dir/link.txt --verbose=1
     1104    [ 36%] Linking CXX executable t_libb64_smoke
     1105    cd /tmp/dewiy/spack-stage/spack-stage-conduit-develop-cmdq4kg4jmo6gmayedefbvbqd3oevnkb/spack-bui
             ld-cmdq4kg/tests/thirdparty && /pfs/lustrep1/appl/lumi/SW/CrayEnv/EB/buildtools/22.08/bin/cmake 
             -E cmake_link_script CMakeFiles/t_libb64_smoke.dir/link.txt --verbose=1
     1106    /opt/cray/pe/craype/2.7.19/bin/CC -O2 -g -DNDEBUG -dynamic CMakeFiles/t_conduit_version.dir/t_co
             nduit_version.cpp.o -o t_conduit_version  -Wl,-rpath,/tmp/dewiy/spack-stage/spack-stage-conduit-
             develop-cmdq4kg4jmo6gmayedefbvbqd3oevnkb/spack-build-cmdq4kg/lib ../../lib/libconduit.so ../../l
             ib/libgtest_main.so ../../lib/libgtest.so
     1107    /opt/cray/pe/craype/2.7.19/bin/CC -O2 -g -DNDEBUG -dynamic CMakeFiles/t_libb64_smoke.dir/t_libb6
             4_smoke.cpp.o "../../thirdparty_builtin/libb64-1.2.1/CMakeFiles/conduit_b64.dir/src/cdecode.cpp.
             o" "../../thirdparty_builtin/libb64-1.2.1/CMakeFiles/conduit_b64.dir/src/cencode.cpp.o" -o t_lib
             b64_smoke  -Wl,-rpath,/tmp/dewiy/spack-stage/spack-stage-conduit-develop-cmdq4kg4jmo6gmayedefbvb
             qd3oevnkb/spack-build-cmdq4kg/lib ../../lib/libgtest_main.so ../../lib/libgtest.so
  >> 1108    ld.lld: error: undefined reference due to --no-allow-shlib-undefined: .omp_offloading.img_start.
             cray_amdgcn-amd-amdhsa
     1109    >>> referenced by ../../lib/libconduit.so
     1110    
  >> 1111    ld.lld: error: undefined reference due to --no-allow-shlib-undefined: .omp_offloading.img_size.c
             ray_amdgcn-amd-amdhsa
     1112    >>> referenced by ../../lib/libconduit.so
     1113    
  >> 1114    ld.lld: error: undefined reference due to --no-allow-shlib-undefined: .omp_offloading.img_cache.
             cray_amdgcn-amd-amdhsa
     1115    >>> referenced by ../../lib/libconduit.so
  >> 1116    clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
  >> 1117    make[2]: *** [tests/conduit/CMakeFiles/t_conduit_smoke.dir/build.make:103: tests/conduit/t_condu
             it_smoke] Error 1
     1118    make[2]: Leaving directory '/tmp/dewiy/spack-stage/spack-stage-conduit-develop-cmdq4kg4jmo6gmaye
             defbvbqd3oevnkb/spack-build-cmdq4kg'
  >> 1119    make[1]: *** [CMakeFiles/Makefile2:1559: tests/conduit/CMakeFiles/t_conduit_smoke.dir/all] Error
              2
     1120    make[1]: *** Waiting for unfinished jobs....
  >> 1121    ld.lld: error: undefined reference due to --no-allow-shlib-undefined: .omp_offloading.img_start.
             cray_amdgcn-amd-amdhsa
     1122    >>> referenced by ../../lib/libconduit.so
     1123    
  >> 1124    ld.lld: error: undefined reference due to --no-allow-shlib-undefined: .omp_offloading.img_size.c
             ray_amdgcn-amd-amdhsa
     1125    >>> referenced by ../../lib/libconduit.so
     1126    
  >> 1127    ld.lld: error: undefined reference due to --no-allow-shlib-undefined: .omp_offloading.img_cache.
             cray_amdgcn-amd-amdhsa
     1128    >>> referenced by ../../lib/libconduit.so
  >> 1129    clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
     1130    make[2]: Leaving directory '/tmp/dewiy/spack-stage/spack-stage-conduit-develop-cmdq4kg4jmo6gmaye
             defbvbqd3oevnkb/spack-build-cmdq4kg'
  >> 1131    make[2]: *** [tests/conduit/CMakeFiles/t_conduit_version.dir/build.make:103: tests/conduit/t_con
             duit_version] Error 1
     1132    make[2]: Leaving directory '/tmp/dewiy/spack-stage/spack-stage-conduit-develop-cmdq4kg4jmo6gmaye
             defbvbqd3oevnkb/spack-build-cmdq4kg'
  >> 1133    make[1]: *** [CMakeFiles/Makefile2:1587: tests/conduit/CMakeFiles/t_conduit_version.dir/all] Err
             or 2
```

**Comment by cyrush** [comment]
Bummer, I usually use:

`spack clean --all`

It's possible something could be hiding `~/.spack` or in a common temp dir.

**Comment by dyokelson** [comment]
Ok sorry I have been nuking everything including the directories you mentioned, completely reinstalled spack and my application, and for some reason it still won't fetch the new version, I wonder if it gets cached somewhere else when the install fails because all the spack packages that installed seem to get fetched anew now...Is there a specific version number for this instead of @develop? I wonder if that might help. Thanks!

**Comment by dyokelson** [comment]
I think I found it! You were right '/tmp/dewiy/spack-stage'. Because all the packages that installed successfully were getting fetched anew but conduit still wasn't so it must be when it fails it stores the binary there and never cleans it even with spack clean --all and deleting all the .spack folders. Ok retrying now again.

**Comment by dyokelson** [comment]
Alright...I think I'm officially losing my mind, after 'rm -rf' on the /tmp/dewiy/spack-stage and .spack* in my home dir, project dir, and application, deleting spack.lock, running spack clean --all, deleting spack, logging out of the node and back in... I reinstall everything and run 'spack -d install' to get verbose output and here is what it says, it looks like it is downloading from the github repo because the spack mirrors fail? But I get the same error still...I'm not really sure I know you're not a spack expert either but I guess let me know if you see anything that doesn't look right here. I may ask the spack group as well.

```
==> [2023-04-16-00:50:08.438963] Processing conduit-develop-b4xb2kwoziqa73tub2rgxrq4xpmr7a2g: task=priority=0, status=dequeued, start=1681594809.327311, #dependencies=2
==> [2023-04-16-00:50:08.441972] Acquiring a write lock on conduit-develop-b4xb2kwoziqa73tub2rgxrq4xpmr7a2g with timeout 1.000ns
==> [2023-04-16-00:50:08.442816] conduit-develop-b4xb2kwoziqa73tub2rgxrq4xpmr7a2g is now write locked
==> [2023-04-16-00:50:08.457369] Creating stage lock spack-stage-conduit-develop-b4xb2kwoziqa73tub2rgxrq4xpmr7a2g
==> [2023-04-16-00:50:08.565044] Installing conduit-develop-b4xb2kwoziqa73tub2rgxrq4xpmr7a2g
==> [2023-04-16-00:50:08.565325] Searching for binary cache of conduit-develop-b4xb2kwoziqa73tub2rgxrq4xpmr7a2g
==> [2023-04-16-00:50:08.566108] Checking existence of https://mirror.spack.io/build_cache/index.json
==> [2023-04-16-00:50:09.239248] Failure reading URL: Download failed: HTTP Error 404: Not Found
==> [2023-04-16-00:50:11.254952] No binary for conduit-develop-b4xb2kwoziqa73tub2rgxrq4xpmr7a2g found: installing from source
==> [2023-04-16-00:50:11.255472] Creating the installation directory /pfs/lustrep2/projappl/project_462000129/spack/opt/spack/linux-sles15-zen2/cce-15.0.0/conduit-develop-b4xb2kwoziqa73tub2rgxrq4xpmr7a2g
==> [2023-04-16-00:50:11.274325] '/usr/bin/git' '-C' '/pfs/lustrep2/projappl/project_462000129/spack' 'rev-parse' 'HEAD'
==> [2023-04-16-00:50:11.426110] Reading config from file /pfs/lustrep2/projappl/project_462000129/soma-collector/spack.yaml
==> [2023-04-16-00:50:11.835692] Using environment '/pfs/lustrep2/projappl/project_462000129/soma-collector'
==> [2023-04-16-00:50:12.306192] Adding compiler bin/ paths: /pfs/lustrep2/projappl/project_462000129/spack/lib/spack/env /pfs/lustrep2/projappl/project_462000129/spack/lib/spack/env/case-insensitive /pfs/lustrep2/projappl/project_462000129/spack/lib/spack/env/cce /pfs/lustrep2/projappl/project_462000129/spack/lib/spack/env/cce/case-insensitive
==> [2023-04-16-00:50:12.413376] A dependency has updated CPATH, this may lead pkg-config to assume that the package is part of the system includes and omit it when invoked with '--cflags'.
==> [2023-04-16-00:50:12.414180] module_cmd.load_module: cray-hdf5
==> [2023-04-16-00:50:13.359666] '/opt/cray/pe/craype/2.7.19/bin/CC' '-v' '/tmp/spack-implicit-link-info7l6zkf8r/main.c' '-o' '/tmp/spack-implicit-link-info7l6zkf8r/output'
==> [2023-04-16-00:50:13.564487] parsing implicit link info
==> [2023-04-16-00:50:13.565201] linker line:  "/opt/cray/pe/cce/15.0.0/cce-clang/x86_64/share/../bin/ld.lld" --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o /tmp/spack-implicit-link-info7l6zkf8r/output /usr/lib/../lib64/crt1.o /usr/lib/../lib64/crti.o /opt/cray/pe/cce/15.0.0/cce-clang/x86_64/lib/clang/15.0.2/lib/linux/clang_rt.crtbegin-x86_64.o -L/opt/cray/pe/libsci/22.12.1.1/CRAY/9.0/x86_64/lib -L/opt/cray/pe/mpich/8.1.23/ofi/cray/10.0/lib -L/opt/cray/pe/mpich/8.1.23/gtl/lib -L/opt/cray/pe/hdf5/1.12.2.1/crayclang/14.0/lib -L/opt/rocm/lib64 -L/opt/rocm/lib -L/opt/rocm/rocprofiler/lib -L/opt/rocm/rocprofiler/tool -L/opt/rocm/roctracer/lib -L/opt/rocm/roctracer/tool -L/opt/rocm/hip/lib -L/opt/cray/xpmem/2.5.2-2.4_3.20__gd0f7936.shasta/lib64 -L/opt/cray/pe/dsmml/0.2.2/dsmml//lib -L/opt/cray/pe/cce/15.0.0/cce/x86_64/lib/pkgconfig/../ -L/opt/gcc/10.3.0/snos/lib64 -L/opt/cray/pe/gcc/10.3.0/snos/lib64 -L/opt/cray/pe/cce/15.0.0/cce/x86_64/lib/pkgconfig/../ -L/opt/cray/pe/gcc/10.3.0/snos/lib/gcc/x86_64-suse-linux/10.3.0 -L/opt/cray/pe/gcc/10.3.0/snos/lib/gcc/x86_64-suse-linux/10.3.0/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/lib -L/usr/lib -plugin-opt=mcpu=znver2 -plugin-opt=lto=0 -plugin-opt=defaults=cray -plugin-opt=mllvm=-cray-math-precision=none -plugin-opt=no-opaque-pointers -rpath=/opt/cray/pe/cce/15.0.0/cce/x86_64/lib -rpath=/opt/cray/pe/gcc-libs /tmp/main-7ae930.o --as-needed -lhdf5_hl --no-as-needed --as-needed -lhdf5 --no-as-needed -lamdhip64 --as-needed -lhdf5_hl_cpp --no-as-needed --as-needed -lhdf5_cpp --no-as-needed --as-needed -lsci_cray_mpi --no-as-needed --as-needed -lsci_cray --no-as-needed -ldl --as-needed -lmpi_cray --no-as-needed -lmpi_gtl_hsa --as-needed -ldsmml --no-as-needed -lxpmem --as-needed -lstdc++ --no-as-needed --as-needed -lpgas-shmem --no-as-needed -lquadmath -lmodules -lfi -lcraymath -lf -lu -lcsup --as-needed -lpthread -latomic --no-as-needed --as-needed -lm --no-as-needed --disable-new-dtags /opt/cray/pe/cce/15.0.0/cce/x86_64/lib/no_mmap.o -lstdc++ -lm /opt/cray/pe/cce/15.0.0/cce-clang/x86_64/lib/clang/15.0.2/lib/linux/libclang_rt.builtins-x86_64.a --as-needed -L/opt/cray/pe/cce/15.0.0/cce-clang/x86_64/lib -rpath=/opt/cray/pe/cce/15.0.0/cce-clang/x86_64/lib /opt/cray/pe/cce/15.0.0/cce-clang/x86_64/lib/libunwind.so -lunwind --no-as-needed -lc /opt/cray/pe/cce/15.0.0/cce-clang/x86_64/lib/clang/15.0.2/lib/linux/libclang_rt.builtins-x86_64.a --as-needed -L/opt/cray/pe/cce/15.0.0/cce-clang/x86_64/lib -rpath=/opt/cray/pe/cce/15.0.0/cce-clang/x86_64/lib /opt/cray/pe/cce/15.0.0/cce-clang/x86_64/lib/libunwind.so -lunwind --no-as-needed /opt/cray/pe/cce/15.0.0/cce-clang/x86_64/lib/clang/15.0.2/lib/linux/clang_rt.crtend-x86_64.o /usr/lib/../lib64/crtn.o
==> [2023-04-16-00:50:13.565393] linkdir: /opt/cray/pe/libsci/22.12.1.1/CRAY/9.0/x86_64/lib
==> [2023-04-16-00:50:13.565456] linkdir: /opt/cray/pe/mpich/8.1.23/ofi/cray/10.0/lib
==> [2023-04-16-00:50:13.565510] linkdir: /opt/cray/pe/mpich/8.1.23/gtl/lib
==> [2023-04-16-00:50:13.565562] linkdir: /opt/cray/pe/hdf5/1.12.2.1/crayclang/14.0/lib
==> [2023-04-16-00:50:13.565613] linkdir: /opt/rocm/lib64
==> [2023-04-16-00:50:13.565664] linkdir: /opt/rocm/lib
==> [2023-04-16-00:50:13.565715] linkdir: /opt/rocm/rocprofiler/lib
==> [2023-04-16-00:50:13.565767] linkdir: /opt/rocm/rocprofiler/tool
==> [2023-04-16-00:50:13.565819] linkdir: /opt/rocm/roctracer/lib
==> [2023-04-16-00:50:13.565879] linkdir: /opt/rocm/roctracer/tool
==> [2023-04-16-00:50:13.565940] linkdir: /opt/rocm/hip/lib
==> [2023-04-16-00:50:13.565997] linkdir: /opt/cray/xpmem/2.5.2-2.4_3.20__gd0f7936.shasta/lib64
==> [2023-04-16-00:50:13.566048] linkdir: /opt/cray/pe/dsmml/0.2.2/dsmml//lib
==> [2023-04-16-00:50:13.566099] linkdir: /opt/cray/pe/cce/15.0.0/cce/x86_64/lib/pkgconfig/../
==> [2023-04-16-00:50:13.566149] linkdir: /opt/gcc/10.3.0/snos/lib64
==> [2023-04-16-00:50:13.566200] linkdir: /opt/cray/pe/gcc/10.3.0/snos/lib64
==> [2023-04-16-00:50:13.566250] linkdir: /opt/cray/pe/cce/15.0.0/cce/x86_64/lib/pkgconfig/../
==> [2023-04-16-00:50:13.566300] linkdir: /opt/cray/pe/gcc/10.3.0/snos/lib/gcc/x86_64-suse-linux/10.3.0
==> [2023-04-16-00:50:13.566354] linkdir: /opt/cray/pe/gcc/10.3.0/snos/lib/gcc/x86_64-suse-linux/10.3.0/../../../../lib64
==> [2023-04-16-00:50:13.566406] linkdir: /lib/../lib64
==> [2023-04-16-00:50:13.566455] linkdir: /usr/lib/../lib64
==> [2023-04-16-00:50:13.566506] linkdir: /lib
==> [2023-04-16-00:50:13.566557] linkdir: /usr/lib
==> [2023-04-16-00:50:13.566682] linkdir: /opt/cray/pe/cce/15.0.0/cce-clang/x86_64/lib
==> [2023-04-16-00:50:13.566742] linkdir: /opt/cray/pe/cce/15.0.0/cce-clang/x86_64/lib
==> [2023-04-16-00:50:13.566807] found raw link dirs: /opt/cray/pe/libsci/22.12.1.1/CRAY/9.0/x86_64/lib, /opt/cray/pe/mpich/8.1.23/ofi/cray/10.0/lib, /opt/cray/pe/mpich/8.1.23/gtl/lib, /opt/cray/pe/hdf5/1.12.2.1/crayclang/14.0/lib, /opt/rocm/lib64, /opt/rocm/lib, /opt/rocm/rocprofiler/lib, /opt/rocm/rocprofiler/tool, /opt/rocm/roctracer/lib, /opt/rocm/roctracer/tool, /opt/rocm/hip/lib, /opt/cray/xpmem/2.5.2-2.4_3.20__gd0f7936.shasta/lib64, /opt/cray/pe/dsmml/0.2.2/dsmml//lib, /opt/cray/pe/cce/15.0.0/cce/x86_64/lib/pkgconfig/../, /opt/gcc/10.3.0/snos/lib64, /opt/cray/pe/gcc/10.3.0/snos/lib64, /opt/cray/pe/cce/15.0.0/cce/x86_64/lib/pkgconfig/../, /opt/cray/pe/gcc/10.3.0/snos/lib/gcc/x86_64-suse-linux/10.3.0, /opt/cray/pe/gcc/10.3.0/snos/lib/gcc/x86_64-suse-linux/10.3.0/../../../../lib64, /lib/../lib64, /usr/lib/../lib64, /lib, /usr/lib, /opt/cray/pe/cce/15.0.0/cce-clang/x86_64/lib, /opt/cray/pe/cce/15.0.0/cce-clang/x86_64/lib
==> [2023-04-16-00:50:13.567151] found link dirs: /opt/cray/pe/libsci/22.12.1.1/CRAY/9.0/x86_64/lib, /opt/cray/pe/mpich/8.1.23/ofi/cray/10.0/lib, /opt/cray/pe/mpich/8.1.23/gtl/lib, /opt/cray/pe/hdf5/1.12.2.1/crayclang/14.0/lib, /opt/rocm/lib64, /opt/rocm/lib, /opt/rocm/rocprofiler/lib, /opt/rocm/rocprofiler/tool, /opt/rocm/roctracer/lib, /opt/rocm/roctracer/tool, /opt/rocm/hip/lib, /opt/cray/xpmem/2.5.2-2.4_3.20__gd0f7936.shasta/lib64, /opt/cray/pe/dsmml/0.2.2/dsmml/lib, /opt/cray/pe/cce/15.0.0/cce/x86_64/lib, /opt/gcc/10.3.0/snos/lib64, /opt/cray/pe/gcc/10.3.0/snos/lib64, /opt/cray/pe/gcc/10.3.0/snos/lib/gcc/x86_64-suse-linux/10.3.0, /lib64, /usr/lib64, /lib, /usr/lib, /opt/cray/pe/cce/15.0.0/cce-clang/x86_64/lib
==> [2023-04-16-00:50:13.587582] Checking existence of https://mirror.spack.io/_source-cache/git/LLNL/conduit.git/develop.tar.gz
==> [2023-04-16-00:50:14.264596] Failure reading URL: Download failed: HTTP Error 404: Not Found
==> [2023-04-16-00:50:14.264884] URL does not exist: https://mirror.spack.io/_source-cache/git/LLNL/conduit.git/develop.tar.gz
==> [2023-04-16-00:50:14.265134] FailedDownloadError: Failed to fetch file from URL: https://mirror.spack.io/_source-cache/git/LLNL/conduit.git/develop.tar.gz
==> [2023-04-16-00:50:14.266438] Checking existence of https://mirror.spack.io/conduit/conduit-develop.tar.gz
==> [2023-04-16-00:50:14.945022] Failure reading URL: Download failed: HTTP Error 404: Not Found
==> [2023-04-16-00:50:14.945258] URL does not exist: https://mirror.spack.io/conduit/conduit-develop.tar.gz
==> [2023-04-16-00:50:14.945454] FailedDownloadError: Failed to fetch file from URL: https://mirror.spack.io/conduit/conduit-develop.tar.gz
==> [2023-04-16-00:50:14.945620] Cloning git repository: https://github.com/LLNL/conduit.git on branch develop
==> [2023-04-16-00:50:14.949990] '/usr/bin/git' '--version'
==> [2023-04-16-00:50:15.043107] '/usr/bin/git' '-c' 'advice.detachedHead=false' '--version'
==> [2023-04-16-00:50:15.150908] '/usr/bin/git' '-c' 'advice.detachedHead=false' '--version'
==> [2023-04-16-00:50:15.270689] '/usr/bin/git' '-c' 'advice.detachedHead=false' 'clone' '--branch' 'develop' '--single-branch' '--depth' '1' 'https://github.com/LLNL/conduit.git'
Cloning into 'conduit'...
remote: Enumerating objects: 1113, done.
remote: Counting objects: 100% (1113/1113), done.
remote: Compressing objects: 100% (892/892), done.
remote: Total 1113 (delta 396), reused 592 (delta 191), pack-reused 0
Receiving objects: 100% (1113/1113), 14.48 MiB | 13.66 MiB/s, done.
Resolving deltas: 100% (396/396), done.
==> [2023-04-16-00:50:17.623948] '/usr/bin/git' '-c' 'advice.detachedHead=false' 'submodule' 'update' '--init' '--recursive'
Submodule 'scripts/uberenv' (https://github.com/LLNL/uberenv.git) registered for path 'scripts/uberenv'
Submodule 'scripts/uberenv_configs/spack_configs' (https://github.com/Alpine-DAV/spack_configs.git) registered for path 'scripts/uberenv_configs/spack_configs'
Submodule 'src/blt' (https://github.com/LLNL/blt.git) registered for path 'src/blt'
Cloning into '/tmp/dewiy/spack-stage/spack-stage-conduit-develop-b4xb2kwoziqa73tub2rgxrq4xpmr7a2g/spack-src/scripts/uberenv'...
Cloning into '/tmp/dewiy/spack-stage/spack-stage-conduit-develop-b4xb2kwoziqa73tub2rgxrq4xpmr7a2g/spack-src/scripts/uberenv_configs/spack_configs'...
Cloning into '/tmp/dewiy/spack-stage/spack-stage-conduit-develop-b4xb2kwoziqa73tub2rgxrq4xpmr7a2g/spack-src/src/blt'...
Submodule path 'scripts/uberenv': checked out '6e4f6b38deae8e8d4a0aaf5667098bf86cc76fea'
Submodule path 'scripts/uberenv_configs/spack_configs': checked out '979ab0c136083082e2fcb86dffdf933391bd2e08'
Submodule path 'src/blt': checked out '84fe0d15d841a79d923e97a9105b86b59147bfed'
==> [2023-04-16-00:50:20.710683] Fetching from https://mirror.spack.io/_source-cache/git/LLNL/conduit.git/develop.tar.gz failed.
==> [2023-04-16-00:50:20.711118] Fetching from https://mirror.spack.io/conduit/conduit-develop.tar.gz failed.
==> [2023-04-16-00:50:20.711582] No checksum needed when fetching with git
==> [2023-04-16-00:50:20.712687] Already staged spack-stage-conduit-develop-b4xb2kwoziqa73tub2rgxrq4xpmr7a2g in /tmp/dewiy/spack-stage/spack-stage-conduit-develop-b4xb2kwoziqa73tub2rgxrq4xpmr7a2g
==> [2023-04-16-00:50:20.712873] No patches needed for conduit
==> [2023-04-16-00:50:20.712977] conduit: Building conduit-develop-b4xb2kwoziqa73tub2rgxrq4xpmr7a2g [CMakePackage]
==> [2023-04-16-00:50:20.797390] conduit: Executing phase: 'cmake'
==> [2023-04-16-00:50:29.658405] conduit: Executing phase: 'build'
==> [2023-04-16-00:53:19.377813] Error: ProcessError: Command exited with status 2:
    'make' '-j16'

55 errors found in build log:
     1083    make[2]: Leaving directory '/tmp/dewiy/spack-stage/spack-stage-conduit-develop-b4xb2kwoziqa73tub2rgxrq4xpmr7a2g/spack-build-b4xb2kw'
     1084    make  -f tests/conduit/CMakeFiles/t_conduit_node_obj_names_with_slashes.dir/build.make tests/conduit/CMakeFiles/t_conduit_node_obj_names_with_sl
             ashes.dir/build
     1085    make[2]: Entering directory '/tmp/dewiy/spack-stage/spack-stage-conduit-develop-b4xb2kwoziqa73tub2rgxrq4xpmr7a2g/spack-build-b4xb2kw'
     1086    [ 34%] Building CXX object tests/conduit/CMakeFiles/t_conduit_node_obj_names_with_slashes.dir/t_conduit_node_obj_names_with_slashes.cpp.o
     1087    cd /tmp/dewiy/spack-stage/spack-stage-conduit-develop-b4xb2kwoziqa73tub2rgxrq4xpmr7a2g/spack-build-b4xb2kw/tests/conduit && /opt/cray/pe/craype/
             2.7.19/bin/CC -DGTEST_HAS_DEATH_TEST=0 -I/tmp/dewiy/spack-stage/spack-stage-conduit-develop-b4xb2kwoziqa73tub2rgxrq4xpmr7a2g/spack-build-b4xb2kw
             /fortran -I/tmp/dewiy/spack-stage/spack-stage-conduit-develop-b4xb2kwoziqa73tub2rgxrq4xpmr7a2g/spack-src/src/libs/conduit -I/tmp/dewiy/spack-sta
             ge/spack-stage-conduit-develop-b4xb2kwoziqa73tub2rgxrq4xpmr7a2g/spack-src/src/libs/conduit/c -I/tmp/dewiy/spack-stage/spack-stage-conduit-develo
             p-b4xb2kwoziqa73tub2rgxrq4xpmr7a2g/spack-build-b4xb2kw/libs/conduit -I/tmp/dewiy/spack-stage/spack-stage-conduit-develop-b4xb2kwoziqa73tub2rgxrq
             4xpmr7a2g/spack-src/src/libs/relay -I/tmp/dewiy/spack-stage/spack-stage-conduit-develop-b4xb2kwoziqa73tub2rgxrq4xpmr7a2g/spack-src/src/libs/rela
             y/c -I/tmp/dewiy/spack-stage/spack-stage-conduit-develop-b4xb2kwoziqa73tub2rgxrq4xpmr7a2g/spack-build-b4xb2kw/libs/relay -I/tmp/dewiy/spack-stag
             e/spack-stage-conduit-develop-b4xb2kwoziqa73tub2rgxrq4xpmr7a2g/spack-src/src/libs/blueprint -I/tmp/dewiy/spack-stage/spack-stage-conduit-develop
             -b4xb2kwoziqa73tub2rgxrq4xpmr7a2g/spack-src/src/libs/blueprint/c -I/tmp/dewiy/spack-stage/spack-stage-conduit-develop-b4xb2kwoziqa73tub2rgxrq4xp
             mr7a2g/spack-build-b4xb2kw/libs/blueprint -I/tmp/dewiy/spack-stage/spack-stage-conduit-develop-b4xb2kwoziqa73tub2rgxrq4xpmr7a2g/spack-src/src/th
             irdparty_builtin/rapidjson/include -I/tmp/dewiy/spack-stage/spack-stage-conduit-develop-b4xb2kwoziqa73tub2rgxrq4xpmr7a2g/spack-src/src/thirdpart
             y_builtin/libb64-1.2.1/include -I/tmp/dewiy/spack-stage/spack-stage-conduit-develop-b4xb2kwoziqa73tub2rgxrq4xpmr7a2g/spack-src/src/thirdparty_bu
             iltin/libyaml-690a781/include -I/tmp/dewiy/spack-stage/spack-stage-conduit-develop-b4xb2kwoziqa73tub2rgxrq4xpmr7a2g/spack-src/src/thirdparty_bui
             ltin/fmt-7.1.0 -I/tmp/dewiy/spack-stage/spack-stage-conduit-develop-b4xb2kwoziqa73tub2rgxrq4xpmr7a2g/spack-src/src/thirdparty_builtin/civetweb-0
             a95342/include -I/tmp/dewiy/spack-stage/spack-stage-conduit-develop-b4xb2kwoziqa73tub2rgxrq4xpmr7a2g/spack-build-b4xb2kw/tests -I/tmp/dewiy/spac
             k-stage/spack-stage-conduit-develop-b4xb2kwoziqa73tub2rgxrq4xpmr7a2g/spack-src/src/blt/thirdparty_builtin/googletest-master-2020-01-07/googletes
             t -isystem /tmp/dewiy/spack-stage/spack-stage-conduit-develop-b4xb2kwoziqa73tub2rgxrq4xpmr7a2g/spack-src/src/blt/thirdparty_builtin/googletest-m
             aster-2020-01-07/googletest/include -O2 -g -DNDEBUG -fPIE -std=c++11 -MD -MT tests/conduit/CMakeFiles/t_conduit_node_obj_names_with_slashes.dir/
             t_conduit_node_obj_names_with_slashes.cpp.o -MF CMakeFiles/t_conduit_node_obj_names_with_slashes.dir/t_conduit_node_obj_names_with_slashes.cpp.o
             .d -o CMakeFiles/t_conduit_node_obj_names_with_slashes.dir/t_conduit_node_obj_names_with_slashes.cpp.o -c /tmp/dewiy/spack-stage/spack-stage-con
             duit-develop-b4xb2kwoziqa73tub2rgxrq4xpmr7a2g/spack-src/src/tests/conduit/t_conduit_node_obj_names_with_slashes.cpp
     1088    make[2]: Leaving directory '/tmp/dewiy/spack-stage/spack-stage-conduit-develop-b4xb2kwoziqa73tub2rgxrq4xpmr7a2g/spack-build-b4xb2kw'
  >> 1089    ld.lld: error: undefined reference due to --no-allow-shlib-undefined: .omp_offloading.img_start.cray_amdgcn-amd-amdhsa
     1090    >>> referenced by ../../lib/libconduit.so
     1091    
  >> 1092    ld.lld: error: undefined reference due to --no-allow-shlib-undefined: .omp_offloading.img_size.cray_amdgcn-amd-amdhsa
     1093    >>> referenced by ../../lib/libconduit.so
     1094    
  >> 1095    ld.lld: error: undefined reference due to --no-allow-shlib-undefined: .omp_offloading.img_cache.cray_amdgcn-amd-amdhsa
     1096    >>> referenced by ../../lib/libconduit.so
     1097    [ 34%] Built target t_libyaml_smoke
     1098    make  -f tests/conduit/CMakeFiles/t_conduit_node_move_and_swap.dir/build.make tests/conduit/CMakeFiles/t_conduit_node_move_and_swap.dir/depend
  >> 1099    clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by cyrush** [comment]
@dyokelson sorry this is so frustrating. 

Q: Does Conduit 0.8.6 build? (conduit@0.8.6)

There was no OpenMP usage in that version --  if we see an .omp_offloading linking error with that version, it could be coming from another library conduit is using  (HDF5 -  but that seems strange)

**Comment by dyokelson** [comment]
Ah good thinking, I get the same error with 0.8.6. We are using an external hdf5 (the module on the machine) rather than downloading it, perhaps it is not compatible? I will try building without hdf5 support.

   ```
 hdf5:
      externals:
      - spec: hdf5@1.12.2.1
        modules: [cray-hdf5]
      buildable: false
```

**Comment by dyokelson** [comment]
Seems to be the same error still even with this in the spack.yaml. Someone told me they don't always trust that spack will actually download and install what you tell it to, haha. I don't know if that's true or not.

 - conduit@0.8.6 ~mpi~silo~hdf5

But it did indeed fetch 0.8.6 at least:
```
==> Installing conduit-0.8.6-hrm2rnj46phbeazmu4divryfgmlimugz
==> conduit exists in binary cache but with different hash
==> No binary for conduit-0.8.6-hrm2rnj46phbeazmu4divryfgmlimugz found: installing from source
==> Warning: There is no checksum on file to fetch conduit@0.8.6 safely.
==>   Fetch anyway? [y/N] y
==> Fetching https://github.com/LLNL/conduit/releases/download/v0.8.6/conduit-v0.8.6-src-with-blt.tar.gz
==> No patches needed for conduit
==> conduit: Executing phase: 'cmake'
==> conduit: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j32'
```

**Comment by cyrush** [comment]
@dyokelson 

Thanks for the updates - I don't think HDF5 even has explicit OpenMP support - so that was a bit of a guess. 

New theory, something is going strange with the compiler.

Are you building with fortran support?

Here is a note about a similar error when adding fortran to the mix 

https://www.mail-archive.com/petsc-dev@mcs.anl.gov/msg27058.html

Can you you try `conduit~fortran`?

Also which version of spack are you using, recent spack develop should have conduit 0.8.6.

(Not sure if it will matter - but newer spack could have better cray support)

**Comment by dyokelson** [comment]
Ah strange, yes that does seem somewhat similar. I will give it a try without fortran today and report back.

I am using spack v0.19, thought it looks like 0.20 is (maybe?) out now.

**Comment by dyokelson** [comment]
I think that worked! At least spack install built successfully! I installed it without fortran, mpi, or silo. 
So `conduit@develop~fortran~silo~mpi`
Thank you!!! I'm working on testing out running the whole stack of software tomorrow.

Follow up question: do you think that building without MPI support could have a negative effect on the performance when serializing the Conduit nodes and sending them via RPC? Especially to other nodes?

**Comment by cyrush** [comment]
Awesome, thanks for your patience working though this! Let me know if I can help if you run into another issue when working with the wider software stack.

With respect to MPI Support - I don't think it will impact your RPC work. 

MPI Support is just one way to transport conduit::Nodes, using another RPC mechanism would be independent. 

That said, how the MPI support is implemented might be interesting to review.

We look for cases where it is possible to zero-copy (directly provide) buffers to the MPI API. This is of course preferred and will be the most efficient way to send the data, but is not always possible. Some times folks present data that isn't contiguous or uses multiple allocations, etc.  In the cases where it is not possible to directly pass buffers, we use conduit to compact the data and pass new contiguous buffers to MPI. 

By reviewing the MPI implementation, you can see examples of logic to identify the various cases and decide which path to use based on the data presented at runtime.

**Comment by dyokelson** [comment]
Ok, great, thank you for all of your help! Yeah, maybe the MPI implementation will be something we try as a follow up. Thanks again!
