### ISSUE TITLE
lib: file not recognized: Is a directory. openmpi/cmake linker problem

### ISSUE THREAD

**Issue by denfromufa** [LLNL/conduit#503]
Cross-posting from LBANN issue:

https://github.com/LLNL/lbann/issues/1439

Trying to build conduit separately to see if the problem comes from LBANN specific settings.

**Comment by cyrush** [comment]
@denfromufa thanks for the report, I suspect something is going wrong with how we detect transitive hdf5 dependencies -- in this case zlib (we are seeing a directory instead of an actual lib)

Can you share details on what type of system this is?
Can you also the output of

`spack spec lbann ^hwloc@1.9`

**Comment by denfromufa** [comment]
This is Power8/P100 node from IBM. What else do you need about the system? By colleague was able to compile conduit with cmake, but with lots of manual adjustments.

```
spack spec lbann ^hwloc@1.9
Input spec
--------------------------------
lbann
    ^hwloc@1.9

Concretized
--------------------------------
lbann@0.99%gcc@7.3.0+al build_type=Release +conduit~docs dtype=float ~extras~gpu~nccl+opencv~seq_init~vtune arch=linux-centos7-skylake_avx512
    ^aluminum@0.3.3%gcc@7.3.0 build_type=RelWithDebInfo ~gpu~mpi_cuda~nccl arch=linux-centos7-skylake_avx512
        ^cmake@3.16.2%gcc@7.3.0~doc+ncurses+openssl+ownlibs~qt arch=linux-centos7-skylake_avx512
            ^ncurses@6.1%gcc@7.3.0~symlinks~termlib arch=linux-centos7-skylake_avx512
                ^pkgconf@1.6.3%gcc@7.3.0 arch=linux-centos7-skylake_avx512
            ^openssl@1.1.1d%gcc@7.3.0+systemcerts arch=linux-centos7-skylake_avx512
                ^perl@5.30.1%gcc@7.3.0+cpanm+shared+threads arch=linux-centos7-skylake_avx512
                    ^gdbm@1.18.1%gcc@7.3.0 arch=linux-centos7-skylake_avx512
                        ^readline@8.0%gcc@7.3.0 arch=linux-centos7-skylake_avx512
                ^zlib@1.2.11%gcc@7.3.0+optimize+pic+shared arch=linux-centos7-skylake_avx512
        ^hwloc@1.9%gcc@7.3.0~cairo~cuda~gl+libxml2~nvml+pci+shared arch=linux-centos7-skylake_avx512
            ^libpciaccess@0.13.5%gcc@7.3.0 arch=linux-centos7-skylake_avx512
                ^libtool@2.4.6%gcc@7.3.0 arch=linux-centos7-skylake_avx512
                    ^m4@1.4.18%gcc@7.3.0 patches=3877ab548f88597ab2327a2230ee048d2d07ace1062efe81fc92e91b7f39cd00,fc9b61654a3ba1a8d6cd78ce087e7c96366c290bc8d2c299f09828d793b853c8 +sigsegv arch=linux-centos7-skylake_avx512
                        ^libsigsegv@2.12%gcc@7.3.0 arch=linux-centos7-skylake_avx512
                ^util-macros@1.19.1%gcc@7.3.0 arch=linux-centos7-skylake_avx512
            ^libxml2@2.9.9%gcc@7.3.0~python arch=linux-centos7-skylake_avx512
                ^libiconv@1.16%gcc@7.3.0 arch=linux-centos7-skylake_avx512
                ^xz@5.2.4%gcc@7.3.0 arch=linux-centos7-skylake_avx512
            ^numactl@2.0.12%gcc@7.3.0 arch=linux-centos7-skylake_avx512
                ^autoconf@2.69%gcc@7.3.0 arch=linux-centos7-skylake_avx512
                ^automake@1.16.1%gcc@7.3.0 arch=linux-centos7-skylake_avx512
        ^ninja@1.10.0%gcc@7.3.0 arch=linux-centos7-skylake_avx512
            ^python@3.7.6%gcc@7.3.0+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4~uuid+zlib arch=linux-centos7-skylake_avx512
                ^bzip2@1.0.8%gcc@7.3.0+shared arch=linux-centos7-skylake_avx512
                    ^diffutils@3.7%gcc@7.3.0 arch=linux-centos7-skylake_avx512
                ^expat@2.2.9%gcc@7.3.0+libbsd arch=linux-centos7-skylake_avx512
                    ^libbsd@0.10.0%gcc@7.3.0 arch=linux-centos7-skylake_avx512
                ^gettext@0.20.1%gcc@7.3.0+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-centos7-skylake_avx512
                    ^tar@1.32%gcc@7.3.0 arch=linux-centos7-skylake_avx512
                ^libffi@3.2.1%gcc@7.3.0 arch=linux-centos7-skylake_avx512
                ^sqlite@3.30.1%gcc@7.3.0~column_metadata+fts~functions~rtree arch=linux-centos7-skylake_avx512
        ^openmpi@3.1.5%gcc@7.3.0~cuda+cxx_exceptions fabrics=none ~java~legacylaunchers~memchecker~pmi schedulers=none ~sqlite3~thread_multiple+vt arch=linux-centos7-skylake_avx512
    ^cereal@1.2.2%gcc@7.3.0 build_type=RelWithDebInfo patches=2dfa0bff9816d0ebd8a1bcc70ced4483b3cda83a982ea5027f1aaadceaa15aac,720265382f29b744488d67e8df5000f2ca1b4dceb2018835fb5dc7a3a1c23f75,91f968e9ac3964e1a689a9ad379ab16f7803ac3d34d24f87ebcaecaa3f9a2f16 arch=linux-centos7-skylake_avx512
    ^clara@1.1.5%gcc@7.3.0 build_type=RelWithDebInfo +single_header arch=linux-centos7-skylake_avx512
    ^cnpy@master%gcc@7.3.0 build_type=RelWithDebInfo arch=linux-centos7-skylake_avx512
    ^conduit@master%gcc@7.3.0~adios~doc~doxygen+fortran+hdf5+hdf5_compat+mpi+python+shared~silo+test~zfp arch=linux-centos7-skylake_avx512
        ^hdf5@1.8.21%gcc@7.3.0~cxx~debug~fortran~hl~mpi+pic+shared~szip~threadsafe arch=linux-centos7-skylake_avx512
        ^py-numpy@1.18.1%gcc@7.3.0+blas+lapack arch=linux-centos7-skylake_avx512
            ^openblas@0.3.8%gcc@7.3.0~ilp64+pic+shared threads=openmp arch=linux-centos7-skylake_avx512
            ^py-cython@0.29.14%gcc@7.3.0 arch=linux-centos7-skylake_avx512
                ^py-setuptools@41.4.0%gcc@7.3.0 arch=linux-centos7-skylake_avx512
    ^hydrogen@1.3.3%gcc@7.3.0+al blas=openblas build_type=Release ~cuda+half+hybrid+int64~int64_blas~mpfr~omp_taskloops+openmp_blas~quad~scalapack+shared~test arch=linux-centos7-skylake_avx512
        ^half@2.1.0%gcc@7.3.0 arch=linux-centos7-skylake_avx512
    ^opencv@4.1.0%gcc@7.3.0 build_type=RelWithDebInfo ~calib3d+core~cuda cuda_arch=none ~cudacodec~dnn~eigen+fast-math~features2d~flann~gtk+highgui+imgproc~ipp~ipp_iw~jasper~java+jpeg~lapack~ml~opencl~opencl_svm~openclamdblas~openclamdfft~openmp+png~powerpc~pthreads_pf~python~qt+shared~stitching~superres+tiff~ts~video~videoio~videostab~vsx~vtk+zlib arch=linux-centos7-skylake_avx512
        ^libjpeg-turbo@2.0.3%gcc@7.3.0 arch=linux-centos7-skylake_avx512
            ^nasm@2.14.02%gcc@7.3.0 arch=linux-centos7-skylake_avx512
        ^libpng@1.6.37%gcc@7.3.0 arch=linux-centos7-skylake_avx512
        ^libtiff@4.0.10%gcc@7.3.0 arch=linux-centos7-skylake_avx512
    ^py-protobuf@3.11.2%gcc@7.3.0+cpp arch=linux-centos7-skylake_avx512
        ^protobuf@3.11.2%gcc@7.3.0 build_type=RelWithDebInfo +shared arch=linux-centos7-skylake_avx512
        ^py-six@1.12.0%gcc@7.3.0 arch=linux-centos7-skylake_avx512

```

**Comment by denfromufa** [comment]
pardon - this is x86_64/V100 node from Dell.

**Comment by cyrush** [comment]
something strange going on here b/c this is a smoke test that should only depend on mpi -- nothing  zlib should get injected.

**Comment by cyrush** [comment]
another question: is this spack develop?

**Comment by cyrush** [comment]
My best guess is that this is an issue with openmpi and possibly cmake 3.16. 

Spack-built openmpi does depend on zlib. Conduit uses cmake's FindMPI to determine all of the flags needed to link with MPI. 

The "blt_mpi_smoke" is a basic exec that tests linking to MPI - its exact purpose to find issues like this one before we try more complex things. 

We have regular CI tests that leverage cmake 3.14 - but not 3.16 (current spack default)

I'll try to test against cmake 3.16 tomorrow. 

Building with mpich may also yield a path forward.

**Comment by denfromufa** [comment]
@cyrush I installed spack as per tutorial 2 days ago:  `git clone https://github.com/spack/spack.git`

specifying cmake 3.14 to spack for conduit help did not help either, I will try other mpi versions.

**Comment by cyrush** [comment]
thanks for ruling out new cmake as a possible factor. I'll try an openmpi build on a linux system to see if I can trigger the same behavior.

**Comment by denfromufa** [comment]
The conduit build completed with mpich, so something is not compatible with openmpi and I would like to know why?! We are using openmpi 4+ at the moment.

```
[@mvpdev01 bin]$ spack install conduit ^cmake@3.14.5 ^mpich
==> pkgconf is already installed in /data/gpfs//condall/spack/opt/spack/linux-centos7-skylake_avx512/gcc-7.3.0/pkgconf-1.6.3-nvqjbgwbrarykezqktkos6pitsqvdudc
==> ncurses is already installed in /data/gpfs//condall/spack/opt/spack/linux-centos7-skylake_avx512/gcc-7.3.0/ncurses-6.1-zu55fwxuu6y4i7vwm5n3mopgetzfb622
==> readline is already installed in /data/gpfs//condall/spack/opt/spack/linux-centos7-skylake_avx512/gcc-7.3.0/readline-8.0-bptawxu6cuy5nv77gtz77jniyzzs6ckf
==> gdbm is already installed in /data/gpfs//condall/spack/opt/spack/linux-centos7-skylake_avx512/gcc-7.3.0/gdbm-1.18.1-zfa35xgyzwwwzbjnf2rfixeuxakku2yj
==> perl is already installed in /data/gpfs//condall/spack/opt/spack/linux-centos7-skylake_avx512/gcc-7.3.0/perl-5.30.1-xwuwfnhm2y4bw3ynkucr3u7nyri2basu
==> zlib is already installed in /data/gpfs//condall/spack/opt/spack/linux-centos7-skylake_avx512/gcc-7.3.0/zlib-1.2.11-dv2dyqdzikigi76fpjq3ii5aqm3h574z
==> openssl is already installed in /data/gpfs//condall/spack/opt/spack/linux-centos7-skylake_avx512/gcc-7.3.0/openssl-1.1.1d-svyowwbat5wlibqez4bvepljthhy63os
==> cmake is already installed in /data/gpfs//condall/spack/opt/spack/linux-centos7-skylake_avx512/gcc-7.3.0/cmake-3.14.5-zwaozeeyqxsan2yvfiwo3vslutuxfx4o
==> hdf5 is already installed in /data/gpfs//condall/spack/opt/spack/linux-centos7-skylake_avx512/gcc-7.3.0/hdf5-1.8.21-t6xgb5jrmwiaejobqvmwqkdsoo6trasn
==> libsigsegv is already installed in /data/gpfs//condall/spack/opt/spack/linux-centos7-skylake_avx512/gcc-7.3.0/libsigsegv-2.12-a2v4fvftdujbuy6a5wbgovsjfqdwqke7
==> m4 is already installed in /data/gpfs//condall/spack/opt/spack/linux-centos7-skylake_avx512/gcc-7.3.0/m4-1.4.18-xy3t3n3bs2rcwipcqypjurethvodiagl
==> autoconf is already installed in /data/gpfs//condall/spack/opt/spack/linux-centos7-skylake_avx512/gcc-7.3.0/autoconf-2.69-w6igxbazug2nmrwp7kq3gpqskonkuhub
==> automake is already installed in /data/gpfs//condall/spack/opt/spack/linux-centos7-skylake_avx512/gcc-7.3.0/automake-1.16.1-d7fxqg6oziwty4hxlvi32yspj6sq5dqk
==> libtool is already installed in /data/gpfs//condall/spack/opt/spack/linux-centos7-skylake_avx512/gcc-7.3.0/libtool-2.4.6-4722qg4r3qv3bn2h24lzlh3maxyqgde2
==> Installing texinfo
==> Searching for binary cache of texinfo
==> No binary for texinfo found: installing from source
==> Fetching https://ftpmirror.gnu.org/texinfo/texinfo-6.5.tar.gz
######################################################################## 100.0%
==> Staging archive: /tmp//spack-stage/spack-stage-texinfo-6.5-ontontfn7qfdgzbxqkts5sofanhrqyvw/texinfo-6.5.tar.gz
==> Created stage in /tmp//spack-stage/spack-stage-texinfo-6.5-ontontfn7qfdgzbxqkts5sofanhrqyvw
==> Applied patch /data/gpfs//condall/spack/var/spack/repos/builtin/packages/texinfo/fix_unescaped_braces.patch
==> Applied patch /data/gpfs//condall/spack/var/spack/repos/builtin/packages/texinfo/update_locale_handling.patch
==> Building texinfo [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Executing phase: 'build'
==> Executing phase: 'install'
==> Successfully installed texinfo
  Fetch: 12.33s.  Build: 51.20s.  Total: 1m 3.53s.
[+] /data/gpfs//condall/spack/opt/spack/linux-centos7-skylake_avx512/gcc-7.3.0/texinfo-6.5-ontontfn7qfdgzbxqkts5sofanhrqyvw
==> Installing findutils
==> Searching for binary cache of findutils
==> No binary for findutils found: installing from source
==> Fetching https://ftpmirror.gnu.org/findutils/findutils-4.6.0.tar.gz
######################################################################## 100.0%
==> Fetching https://src.fedoraproject.org/rpms/findutils/raw/97ba2d7a18d1f9ae761b6ff0b4f1c4d33d7a8efc/f/findutils-4.6.0-gnulib-fflush.patch
######################################################################## 100.0%
==> Fetching https://src.fedoraproject.org/rpms/findutils/raw/97ba2d7a18d1f9ae761b6ff0b4f1c4d33d7a8efc/f/findutils-4.6.0-gnulib-makedev.patch
######################################################################## 100.0%
==> Staging archive: /tmp//spack-stage/spack-stage-findutils-4.6.0-grw2tsvioq4rnxojfhd6rn7gii6hcgvz/findutils-4.6.0.tar.gz
==> Created stage in /tmp//spack-stage/spack-stage-findutils-4.6.0-grw2tsvioq4rnxojfhd6rn7gii6hcgvz
==> Applied patch https://src.fedoraproject.org/rpms/findutils/raw/97ba2d7a18d1f9ae761b6ff0b4f1c4d33d7a8efc/f/findutils-4.6.0-gnulib-fflush.patch
==> Applied patch https://src.fedoraproject.org/rpms/findutils/raw/97ba2d7a18d1f9ae761b6ff0b4f1c4d33d7a8efc/f/findutils-4.6.0-gnulib-makedev.patch
==> Ran patch() for findutils
==> Building findutils [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Executing phase: 'build'
==> Executing phase: 'install'
==> Successfully installed findutils
  Fetch: 6.53s.  Build: 1m 22.23s.  Total: 1m 28.76s.
[+] /data/gpfs//condall/spack/opt/spack/linux-centos7-skylake_avx512/gcc-7.3.0/findutils-4.6.0-grw2tsvioq4rnxojfhd6rn7gii6hcgvz
==> util-macros is already installed in /data/gpfs//condall/spack/opt/spack/linux-centos7-skylake_avx512/gcc-7.3.0/util-macros-1.19.1-xjh3llu33doh3pze2k4xx452wbzuroem
==> libpciaccess is already installed in /data/gpfs//condall/spack/opt/spack/linux-centos7-skylake_avx512/gcc-7.3.0/libpciaccess-0.13.5-bkmql2puvsbqfwzrfyh4uqaftx67ksqd
==> libiconv is already installed in /data/gpfs//condall/spack/opt/spack/linux-centos7-skylake_avx512/gcc-7.3.0/libiconv-1.16-lmdf36vwnegxn6vyxgfnuynbwyaiulcj
==> xz is already installed in /data/gpfs//condall/spack/opt/spack/linux-centos7-skylake_avx512/gcc-7.3.0/xz-5.2.4-mhqwgog2epxq742ebgawtdwml6o4j2qv
==> libxml2 is already installed in /data/gpfs//condall/spack/opt/spack/linux-centos7-skylake_avx512/gcc-7.3.0/libxml2-2.9.9-f7id5qm5yxwacuy2xz4qrnep3yqylvvj
==> Installing mpich
==> Searching for binary cache of mpich
==> No binary for mpich found: installing from source
==> Fetching http://www.mpich.org/static/downloads/3.3.2/mpich-3.3.2.tar.gz
######################################################################## 100.0%
==> Staging archive: /tmp//spack-stage/spack-stage-mpich-3.3.2-ssaeisxddzecprarsub44lpyv5jsq6c4/mpich-3.3.2.tar.gz
==> Created stage in /tmp//spack-stage/spack-stage-mpich-3.3.2-ssaeisxddzecprarsub44lpyv5jsq6c4
==> No patches needed for mpich
==> Building mpich [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Executing phase: 'build'
==> Executing phase: 'install'
==> Successfully installed mpich
  Fetch: 23.82s.  Build: 3m 22.36s.  Total: 3m 46.19s.
[+] /data/gpfs//condall/spack/opt/spack/linux-centos7-skylake_avx512/gcc-7.3.0/mpich-3.3.2-ssaeisxddzecprarsub44lpyv5jsq6c4
==> openblas is already installed in /data/gpfs//condall/spack/opt/spack/linux-centos7-skylake_avx512/gcc-7.3.0/openblas-0.3.8-bnem26bie3h2uqoked5xisdeiqly67h5
==> diffutils is already installed in /data/gpfs//condall/spack/opt/spack/linux-centos7-skylake_avx512/gcc-7.3.0/diffutils-3.7-dartwbsvg4id4y7n62jf5yxxt6a6hyso
==> bzip2 is already installed in /data/gpfs//condall/spack/opt/spack/linux-centos7-skylake_avx512/gcc-7.3.0/bzip2-1.0.8-2pwudt72wc5u72xil24f2q4rcmobon6t
==> libbsd is already installed in /data/gpfs//condall/spack/opt/spack/linux-centos7-skylake_avx512/gcc-7.3.0/libbsd-0.10.0-ktdp7abpwcjrhfzwwpr36dznkwlggkqj
==> expat is already installed in /data/gpfs//condall/spack/opt/spack/linux-centos7-skylake_avx512/gcc-7.3.0/expat-2.2.9-cqi7rkyomz76cnkx4hlxwe6xtf4ozcmj
==> tar is already installed in /data/gpfs//condall/spack/opt/spack/linux-centos7-skylake_avx512/gcc-7.3.0/tar-1.32-fckqzabpsverodm6r33kihy7ovkbevwi
==> gettext is already installed in /data/gpfs//condall/spack/opt/spack/linux-centos7-skylake_avx512/gcc-7.3.0/gettext-0.20.1-uqeja5qwbjuied5qdv5izkanc4jtmjoa
==> libffi is already installed in /data/gpfs//condall/spack/opt/spack/linux-centos7-skylake_avx512/gcc-7.3.0/libffi-3.2.1-sfr3r4aikcpilsysguzo6z6q4uwmmu6a
==> sqlite is already installed in /data/gpfs//condall/spack/opt/spack/linux-centos7-skylake_avx512/gcc-7.3.0/sqlite-3.30.1-2wvbdcdzbmstkkoi32jtqh3q67i4b4ek
==> python is already installed in /data/gpfs//condall/spack/opt/spack/linux-centos7-skylake_avx512/gcc-7.3.0/python-3.7.6-djlkfk46fulgonuulepryp3voextxbbi
==> py-setuptools is already installed in /data/gpfs//condall/spack/opt/spack/linux-centos7-skylake_avx512/gcc-7.3.0/py-setuptools-41.4.0-7gnnipc7sypox2wdbg6uvtxkbf4emue3
==> py-cython is already installed in /data/gpfs//condall/spack/opt/spack/linux-centos7-skylake_avx512/gcc-7.3.0/py-cython-0.29.14-basqbqaym4zgkrlndzzwffckssf2v6ob
==> py-numpy is already installed in /data/gpfs//condall/spack/opt/spack/linux-centos7-skylake_avx512/gcc-7.3.0/py-numpy-1.18.1-gdusvn42kgnnthgaoymd5ykmgoryqaqh
==> Installing conduit
==> Searching for binary cache of conduit
==> No binary for conduit found: installing from source
==> Cloning git repository: https://github.com/LLNL/conduit.git on branch master
==> No checksum needed when fetching with git
==> Already staged spack-stage-conduit-master-aehrkz46yume7e2aroha245quklr24r5 in /tmp//spack-stage/spack-stage-conduit-master-aehrkz46yume7e2aroha245quklr24r5
==> No patches needed for conduit
==> Building conduit [Package]
==> Executing phase: 'configure'
==> Executing phase: 'build'
==> Executing phase: 'install'
==> Successfully installed conduit
  Fetch: 29.29s.  Build: 58.63s.  Total: 1m 27.92s.
[+] /data/gpfs//condall/spack/opt/spack/linux-centos7-skylake_avx512/gcc-7.3.0/conduit-master-aehrkz46yume7e2aroha245quklr24r5

```

**Comment by cyrush** [comment]
Thanks for the update. 

If you look at the spack-built openmpi, I suspect the `showme` flags from the mpi compiler wrappers are the source of the bad link dir.  It could be an issue with how spack configures and build's openmpi on your system. System zlib might be creeping in.  (My openmpi build is still underway on our cluster)

You mention openmpi 4 - however spack is currently building 3.1.5. Do you have a system install of openmpi that you want to use? If so, you will want to tell spack to use your existing mpi via a `packages.yaml ` file.

Here is an example that we use to use a system mvapich for one of our LLNL clusters: 

https://github.com/Alpine-DAV/ascent/blob/develop/scripts/uberenv/spack_configs/llnl/pascal_cuda/packages.yaml

That will prevent spack from building it (and its dependencies) and use your install instead.

**Comment by cyrush** [comment]
my openmpi test replicated the issue -- so I'll be able to dive in more

**Comment by cyrush** [comment]
I figured out what is going on.

openmpi compiler wrappers *are* reporting the correct info to CMake.

CMake's FindMPI has logic to remove duplicate strings in the linker flags. That is undermining us. 

basically, the following output from the mpi compiler wrappers:

```
-Wl,-rpath -Wl,/usr/WS1/cyrush/2020.02.spack/spack/opt/spack/linux-rhel7-broadwell/gcc-4.9.3/hwloc-1.9-d4zgaf6umszt34dljhrq7bawwpi2bdut/lib
-Wl,-rpath -Wl,/usr/WS1/cyrush/2020.02.spack/spack/opt/spack/linux-rhel7-broadwell/gcc-4.9.3/zlib-1.2.11-odisvif7tj74k7ze6wwmcibh2ci2re3a/lib
-Wl,-rpath -Wl,/usr/lib64
-Wl,-rpath -Wl,/usr/WS1/cyrush/2020.02.spack/spack/opt/spack/linux-rhel7-broadwell/gcc-4.9.3/openmpi-3.1.5-uwwxzib75h6lnq5lzbe2hkm2higvgzci/lib
```

gets transformed into:

```
-Wl,-rpath -Wl,/usr/WS1/cyrush/2020.02.spack/spack/opt/spack/linux-rhel7-broadwell/gcc-4.9.3/hwloc-1.9-d4zgaf6umszt34dljhrq7bawwpi2bdut/lib 
-Wl,/usr/WS1/cyrush/2020.02.spack/spack/opt/spack/linux-rhel7-broadwell/gcc-4.9.3/zlib-1.2.11-odisvif7tj74k7ze6wwmcibh2ci2re3a/lib
-Wl,/usr/lib64
-Wl,/usr/WS1/cyrush/2020.02.spack/spack/opt/spack/linux-rhel7-broadwell/gcc-4.9.3/openmpi-3.1.5-uwwxzib75h6lnq5lzbe2hkm2higvgzci/lib
```
(in this case I used cmake 3.14)
The dropped `-Wl,-rpath` commands create malformed linker input. 

I tested with CMake 3.9 and it works, this is a regression with newer cmake versions. 

I seem to recall echoes of this type of problem with FindMPI -- I'll try to report to CMake folks. 

In the mean time, there may be something we can do to try to mitigate the problem -- I'll ponder a bit. I won't be able to sink any more time into this until next week.

**Comment by denfromufa** [comment]
@cyrush I cannot build lbann with openmpi and cmake@3.9, hydrogen is requesting cmake 3.12+:

```
==> Installing hydrogen
==> Searching for binary cache of hydrogen
==> No binary for hydrogen found: installing from source
==> Cloning git repository: https://github.com/LLNL/Elemental.git on branch hydrogen
==> No checksum needed when fetching with git
==> Already staged spack-stage-hydrogen-develop-h6kamoyhcgkw4w3fmcxwah5blsjichrw in /tmp/j0541825/spack-stage/spack-stage-hydrogen-develop-h6kamoyhcgkw4w3fmcxwah5blsjichrw
==> No patches needed for hydrogen
==> Building hydrogen [CMakePackage]
==> Executing phase: 'cmake'
==> Error: ProcessError: Command exited with status 1:

...

1 error found in build log:
  >> 3    CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
     4      CMake 3.12 or higher is required.  You are running version 3.9.6
     5    
     6    
     7    -- Configuring incomplete, errors occurred!

See build log for details:

```

**Comment by cyrush** [comment]
@denfromufa I think I have a solution for this -- updating to a newer BLT -- which we use to call FindMPI avoids de-duplication of rpath commands. 

I tested with cmake 3.14, and I will test shortly for 3.16 as well

**Comment by cyrush** [comment]
@denfromufa with the BLT update in #507,  I tested cmake 3.12, 3.13, 3.14, and 3.16 and did not hit the issue.  Pending our CI tests, I will merge this into master and let you know. 

After the merge -- conduit@master should build for you again via spack with openmpi.

**Comment by cyrush** [comment]
@denfromufa this should be resolved in conduit master. Thanks for your help with identifying the issue!

**Comment by denfromufa** [comment]
@cyrush I confirm that this is resolved! thank you for quick fix..

**Comment by cyrush** [comment]
@denfromufa great - glad this helped & thanks for confirming!

**Comment by saikat007** [comment]
@cyrush , When trying to install conduit using spack, I get the following errors:

```
838     /usr/bin/ld: warning: libgfortran.so.5, needed by ../../lib/libconduit.so, not found (try using -rpath or -rpath
             -link)
  >> 839     ../../lib/libconduit.so: undefined reference to `_gfortran_string_trim@@GFORTRAN_8'
  >> 840     ../../lib/libconduit.so: undefined reference to `_gfortran_string_len_trim@@GFORTRAN_8'
  >> 841     ../../lib/libconduit.so: undefined reference to `_gfortran_concat_string@@GFORTRAN_8'
  >> 842     collect2: error: ld returned 1 exit status
  >> 843     make[2]: *** [tests/conduit/t_conduit_smoke] Error 1
     844     make[2]: Leaving directory `/tmp/saikatm/spack-stage/spack-stage-conduit-master-j4ucnaekdhmppqvzcabp2ih25wizybmd
             /spack-src/spack-build'
  >> 845     make[1]: *** [tests/conduit/CMakeFiles/t_conduit_smoke.dir/all] Error 2
```
I have already set the path `/usr/local/gnu/8.4.0/lib64` (which contains libgfortran.so.5) in LD_LIBRARY_PATH but still getting that error. Any ideas on how to solve this?

**Comment by mclarsen** [comment]
If you don't need fortran you can build conduit with `~fortran`.

**Comment by saikat007** [comment]
Thanks, that worked. I am also getting another error when in installing py-protobuf when trying to build and install LBANN using spack:

```
  >> 105    /usr/bin/ld: cannot find -lprotobuf
  >> 106    collect2: error: ld returned 1 exit status
  >> 107    error: command '/usr/local/gnu/8.4.0/bin/g++' failed with exit status 1
```

I checked my `/usr/lib64` and there is a libprotobuf file, which I again added to `LIBRARY_PATH`. Any help in solving this will be highly appreciated.

**Comment by mclarsen** [comment]
Is `protobuf` a conduit dependency?

**Comment by mclarsen** [comment]
I also don't know if spack respect what you put into `LD_LIBRARY_PATH`

**Comment by saikat007** [comment]
No Conduit and py-protobuf are dependencies for LBANN. And I am getting error when trying to install LBANN using spack for these two dependencies. When I try to install conduit and py-protobuf standalone using spack that works, but when I issue: `spack install lbann ^hwloc@1.9`, I get the errors I showed above both for conduit and protobuf.

**Comment by mclarsen** [comment]
Unfortunately, I don't know anything about the LBANN spack package.

**Comment by saikat007** [comment]
I understand I will make this a separate issue.

**Comment by cyrush** [comment]
@saikat007 I don't expect spack to honor `LD_LIBRARY_PATH` by default.   If you want to use a system version of protobuf, I think you need to configure spack to look for it as an external package and provide the paths. Depending on how you are calling spack, the machinery to specify as external will be different -- and I'll admit I only know old ways -- I would ask spack folks for latest guidance on their slack. 

For the fortran issue, @mclarsen's suggestion to disable fortran is good, since I don't belive LBANN needs conduit's fortran support for anything. It does make me think the compiler setup in spack might need some extra rpath flags when fortran is being used. Since it's not a blocker for you, not sure we need to fully understand on your system.

**Comment by saikat007** [comment]
Yep conduit by itself using spack installs when I do: `spack install conduit ~fortran`.
But it gives the same [error](https://github.com/LLNL/conduit/issues/503#issuecomment-706638646) again when I do: `spack install lbann ^hwloc@1.9`.
I posted a detailed issue here: https://github.com/LLNL/lbann/issues/1663. Been trying to install lbann for a few dows now but nothing is working to fix those two package installation.
